### ISSUE TITLE
Uncaught Error: Call to undefined function getallheaders()

### ISSUE THREAD

**Issue by chromahoen** [raelshark/gf-referrer#2]
Glad that you wrote this. Thank you... After installing in 5.3.2, I get an error just loading the site. Even loading while not on the page that holds the form. Any ideas?

WordPress version 5.3.2
Current theme: UnderStrap Child (version 0.5.0)
Current plugin: Referrer Field for Gravity Forms (version 1.0.1)
PHP version 7.1.17

Error Details
=============
An error of type E_ERROR was caused in line 24 of the file
/opt/bitnami/nginx/html/wp-content/plugins/gf-referrer-master/gf-referrer.php.
Error message: Uncaught Error: Call to undefined function
getallheaders() in
/opt/bitnami/nginx/html/wp-content/plugins/gf-referrer-master/gf-referrer.php:24
Stack trace:
#0 /opt/bitnami/nginx/html/wp-content/plugins/gf-referrer-master/gf-referrer.php(45):
get_referrer()
#1 /opt/bitnami/nginx/html/wp-includes/class-wp-hook.php(288):
set_referrer_cookie('')
#2 /opt/bitnami/nginx/html/wp-includes/class-wp-hook.php(312):
WP_Hook->apply_filters(NULL, Array)
#3 /opt/bitnami/nginx/html/wp-includes/plugin.php(478):
WP_Hook->do_action(Array)
#4 /opt/bitnami/nginx/html/wp-settings.php(523): do_action('init')
#5 /opt/bitnami/nginx/html/wp-config.php(108):
require_once('/opt/bitnami/ng...')
#6 /opt/bitnami/nginx/html/wp-load.php(37): require_once('/opt/bitnami/ng...')
#7 /opt/bitnami/nginx/html/wp-login.php(12): require('/opt/bitnami/ng...')
#8 {main}
  thrown

**Comment by sc456a** [comment]
This plugin doesn't work - it's just something we were testing. We have a new version in development but no eta on the release at this time.

**Comment by chromahoen** [comment]
Looking forward to that. Thank you.
